version: '3.8'

services:
  solr:
    build:
      context: ./data_retrieval
    container_name: solr
    ports:
      - "8983:8983"
  fastapi:
    build:
      context: ./api
    container_name: fastapi
    ports:
      - "5000:5000"
    depends_on:
      - solr
    links:
      - solr
  react:
    build:
      context: ./frontend
    container_name: react
    ports:
      - "3000:3000"
    depends_on:
      - fastapi


volumes:
  solr_data: